# Generated by Django 5.1.4 on 2024-12-08 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='events_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('eventname', models.CharField(max_length=100)),
                ('eventdate', models.CharField(max_length=9)),
                ('eventtime', models.CharField(max_length=100)),
            ],
        ),
    ]
