# Generated by Django 5.1.4 on 2024-12-08 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_events_1'),
    ]

    operations = [
        migrations.CreateModel(
            name='edit_events',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('eventname', models.CharField(max_length=100)),
                ('eventdate', models.CharField(max_length=9)),
                ('eventtime', models.CharField(max_length=100)),
            ],
        ),
    ]
